openapi: 3.0.0
info:
  title: Yoonhae's API
  description: express study and test api
  version: 0.1.9
servers:
  - url: http://127.0.0.1:3000
    description: local server

paths:
  /book:
    $ref: './service/book/swagger-doc.yaml'

  /user:
    $ref: './service/user/swagger-doc.yaml'
