openapi: 3.0.0
info:
  title: Yoonhae's API
  description: express study and test api
  version: 0.1.9
servers:
  - url: http://127.0.0.1:3000
    description: local server

paths:
  /auth:
    get:
      tags:
        - ./swagger.yaml 파일
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/test"